robocode:
  home: "/home/patryk/robocode"
  instances: 1
  tps: 150
  gui: true
  battle_file: "train.battle"
  my_robot_name: "pl.agh.edu.plato.PlatoRobot*"
  opponents: ["sample.SittingDuck"]

  num_rounds: 1000
  inactivity_time: 3000
  gun_cooling_rate: 0.1
  battlefield_width: 800
  battlefield_height: 600

server:
  ip: "127.0.0.1"
  learn_port: 8000
  weight_port: 8001
  python_exe: "python3"
  script_name: "main.py"

logging:
  log_dir: "./logs"
  python_log_level: "INFO"

tensorboard:
  bind_all: false

project_paths:
  server_dir: "plato-server"
  maven_project_dir: "plato-robot"
