server:
  ip: "127.0.0.1"
  learningPort: 8000
  weightPort: 8001

rl:
  explorationEpsilonMax: 1.0
  explorationEpsilonMin: 0.01
  explorationEpsilonDecrease: 0.0007

timing:
  actionInterval: 5
  networkReloadInterval: 50

rewards:
  survival: 0.02
  hitMultiplier: 10.0
  penaltyGotHitMultiplier: -10.0
  penaltyHitWall: -4.0
  standingStillPenalty: -0.2
  approachEnemy: 0.1
  retreatEnemyPenalty: -0.1
  gunHeatPenalty: -1.0
  aimedReady: 0.2
  energyRetention: 0.01
  win: 20.0
  penaltyDeath: -20.0