server:
  ip: "127.0.0.1"
  learningPort: 8000
  weightPort: 8001

rl:
  explorationEpsilonMax: 1.0
  explorationEpsilonMin: 0.01
  explorationEpsilonDecrease: 0.002

timing:
  networkReloadInterval: 1000
  actionInterval: 10

rewards:
  hitMultiplier: 5.0
  survival: -0.2
  aimedReady: 5.0
  penaltyGotHitMultiplier: 3.0
  penaltyHitWall: 5.0
  penaltyDeath: 40.0
  win: 50.0
